# Generated by Django 3.2.5 on 2021-09-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_subscription_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("location", models.CharField(max_length=300)),
                ("scheduled_at", models.DateTimeField()),
            ],
        ),
    ]
