# Generated by Django 3.2.5 on 2021-09-13 13:16

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Subscription = apps.get_model("main", "Subscription")
    for row in Subscription.objects.all():
        row.unsubscribe_key = uuid.uuid4()
        row.save(update_fields=["unsubscribe_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_add_subscription_unsubscribe_key"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
