# Generated by Django 3.2.5 on 2021-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_subscription_unsubscribe_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailrecord",
            name="email",
            field=models.EmailField(default="nobody@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
