# Generated by Django 3.2.5 on 2021-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_emailrecord_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="gmaps_url",
            field=models.URLField(default="http://g.co/"),
            preserve_default=False,
        ),
    ]
