# Generated by Django 3.2.5 on 2021-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_event_gmaps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="body",
            field=models.TextField(default=None, null=True),
        ),
    ]
