# Generated by Django 3.2.5 on 2021-09-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_event_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="gmaps_url",
            new_name="location_url",
        ),
    ]
